# -*- coding: utf-8 -*-
"""patch_embedding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOwXtdzH9paBoQJU9IcWGJFPGciFOb6Q
"""

"""
patch_embedding.py
==================
Première étape d'un Vision Transformer : transformer une image en séquence de tokens.

Idée fondamentale :
    Une image 32x32 avec patch_size=4 donne (32/4)^2 = 64 patches.
    Chaque patch (4x4x3 = 48 pixels) est projeté linéairement vers embed_dim.

Pourquoi Conv2d comme projection ?
    Conv2d(in_channels, embed_dim, kernel_size=patch_size, stride=patch_size)
    est mathématiquement équivalente à une projection linéaire sur chaque patch.
"""

import torch
import torch.nn as nn


class PatchEmbedding(nn.Module):
    def __init__(self, img_size=32, patch_size=4, in_channels=3, embed_dim=128):
        super().__init__()
        assert img_size % patch_size == 0, "img_size doit être divisible par patch_size"
        self.patch_size = patch_size
        self.num_patches = (img_size // patch_size) ** 2   # 64 patches pour 32x32, patch=4
        self.projection = nn.Conv2d(
            in_channels=in_channels,
            out_channels=embed_dim,
            kernel_size=patch_size,
            stride=patch_size,
        )

    def forward(self, x):
        # x : (B, C, H, W)
        x = self.projection(x)   # → (B, embed_dim, H/P, W/P)
        x = x.flatten(2)         # → (B, embed_dim, num_patches)
        x = x.transpose(1, 2)   # → (B, num_patches, embed_dim)  ← format séquence
        return x