# -*- coding: utf-8 -*-
"""metrics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOwXtdzH9paBoQJU9IcWGJFPGciFOb6Q
"""

"""
metrics.py — Utilitaires de mesure des performances.
"""
import torch


def compute_accuracy(logits, targets):
    """
    Accuracy top-1.
    argmax(logits) == argmax(softmax(logits)) car softmax est monotone.
    """
    with torch.no_grad():
        preds = logits.argmax(dim=1)
        return (preds == targets).float().mean().item()


class AverageMeter:
    """Accumule une métrique sur une époque et calcule la moyenne pondérée."""
    def __init__(self):
        self.reset()

    def reset(self):
        self.sum = 0.0
        self.count = 0

    def update(self, val, n=1):
        self.sum   += val * n
        self.count += n

    @property
    def avg(self):
        return self.sum / self.count if self.count > 0 else 0.0